version: '3.7'

services:
  web:
    build: .
    #volumes:
      #- ./src:/var/www/html
      #- ./vendor:/var/www/vendor
      #- ./db/appreciations.sqlite:/var/www/db/appreciations.sqlite
    ports:
      - "8080:8080"