version: '3.7'

services:
  web:
    build: .
    environment:
      - SECRET=opensesame
      - NAMES=Alice,Bob
      - DEVELOPMENT=false
    volumes:
      - ./db/appreciations.sqlite:/var/www/db/appreciations.sqlite
    ports:
      - "8080:8080"