name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Publish Docker Image
      uses: matootie/github-docker@v3.0.0
      with:
        accessToken: ${{ github.token }}